project:
  type: website

website:
  title: "Open Séance"
  repo-url: "https://github.com/ghostCollective/open-seance"
  site-url: "https://ghostCollective.github.io/open-seance"
  page-footer: 
    center: "Made with 👻 and Quarto"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - text: Cards
        menu: 
          - href: technical-cards.qmd
            text: "Technical cards"
          - href: experience-cards.qmd
            text: "Experience cards"
      #- href: cards.qmd
        #text: "Cards"
      - href: rules.qmd
        text: "Rules"
    right: 
      - icon: github
        href: https://github.com/ghostCollective/open-seance
        aria-label: GitHub

format:
  html:
    theme: 
      dark: night-seance.scss
      light: day-seance.scss
    toc: true
    include-after-body: assets/partials/footer.html

