# Experience cards
## Spaghetti code {#spaghetti-code}
<https://blog.esciencecenter.nl/researchers-are-not-born-engineers-why-are-they-expected-to-know-how-to-code-1eeb5c3d03c0>

## Science done wrong {#science-done-wrong}
<https://retractionwatch.com/the-retraction-watch-leaderboard/top-10-most-highly-cited-retracted-papers>

## Flawless replication {#flawless-replication}
<https://blog.khinsen.net/posts/2025/06/20/computational-reproducibility.html>

## Coding with my crush {#coding-with-my-crush}
<NA>

## A standout researcher with 200+ retractions {#a-standout-researcher-with-200-retractions}
<https://retractionwatch.com/category/joachim-boldt-retractions/>

## 10k stars on GitHub {#x10k-stars-on-git-hub}
<https://book.the-turing-way.org/collaboration/github-novice/github-novice-features/#using-github-features-to-foster-collaboration>

## Second author {#second-author}
<NA>

## Retraction watch leaderboard {#retraction-watch-leaderboard}
<https://retractionwatch.com/the-retraction-watch-leaderboard/>

## Science done right {#science-done-right}
<NA>

## Data privacy audits {#data-privacy-audits}
<NA>

## PhD-level AI {#ph-d-level-ai}
<https://www.oneusefulthing.org/p/what-just-happened>

## Citeable code {#citeable-code}
<https://www.esciencecenter.nl/news/code-citation-was-made-possible-by-research-software-engineers-in-germany-and-the-netherlands/>

## Restrictive university guidelines {#restrictive-university-guidelines}
<NA>

## Copyright conundrums {#copyright-conundrums}
<NA>

## EU-wide bans {#eu-wide-bans}
<NA>

## Shadow IT {#shadow-it}
<NA>

## Failing ethically {#failing-ethically}
<NA>

## 0 hour contracts {#x0-hour-contracts}
<NA>

## Open Science Games {#open-science-games}
<https://ghostcollective.github.io/games.html>

## Amateur scientists {#amateur-scientists}
<NA>

## Open Science badges {#open-science-badges}
<https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1002456>

## Supplementary materials {#supplementary-materials}
<NA>

## Interoperable caffeine pills {#interoperable-caffeine-pills}
<NA>

## Sensitive data on shady cloud services {#sensitive-data-on-shady-cloud-services}
<NA>

## P-hacking {#p-hacking}
<NA>

## Coding Café {#coding-cafe}
<https://code-cafes-nl.github.io/cafe_playbook/>

## Publishing null results {#publishing-null-results}
<https://blog.ssrn.com/2023/10/26/being-positive-about-the-negative>

## Installation instructions {#installation-instructions}
<https://www.makeareadme.com/>

## Paywalled journals {#paywalled-journals}
<NA>

## Publishing raw data {#publishing-raw-data}
<NA>

## Data as the most important research output {#data-as-the-most-important-research-output}
<NA>

## APC waiver {#apc-waiver}
<NA>

## Open, but broke {#open-but-broke}
<NA>

## Buy this article {#buy-this-article}
<NA>

## Gatekeeping {#gatekeeping}
<NA>

## Dear Esteemed Professor/Respected Researcher/Dr. ... {#dear-esteemed-professor-respected-researcher-dr}
<NA>

## Tutorials developed by the community {#tutorials-developed-by-the-community}
<https://book.the-turing-way.org/>

## Journal flipping {#journal-flipping}
<NA>

## Profit over science {#profit-over-science}
<NA>

## Diamond Open Access is my hobby {#diamond-open-access-is-my-hobby}
<NA>

## Citation gap {#citation-gap}
<NA>

## Publisher prestige {#publisher-prestige}
<NA>

## Supervisor ghosting {#supervisor-ghosting}
<NA>

## Code version history {#code-version-history}
<https://book.the-turing-way.org/reproducible-research/vcs/>

## Lost in translation {#lost-in-translation}
<NA>

## 'It's the incentives, stupid' {#its-the-incentives-stupid}
<https://doi.org/10.7557/5.7153>

## final_rev18_v2_withoutComments.pdf {#final-rev18-v2-without-comments-pdf}
<NA>

## Code that only works on my computer {#code-that-only-works-on-my-computer}
<NA>

## A variable named 'temp' {#a-variable-named-temp}
<NA>

## European AI {#european-ai}
<NA>

## Yelling at ChatGPT {#yelling-at-chat-gpt}
<NA>

## Legal hot water {#legal-hot-water}
<NA>

## LLMs hallucinating references {#llms-hallucinating-references}
<https://www.youtube.com/watch?v=_zfN9wnPvU0>

## Power analysis {#power-analysis}
<https://daniellakens.blogspot.com/2017/05/how-power-analysis-implicitly-reveals.html>

## Impostor Syndrome {#impostor-syndrome}
<NA>

## Expensive proprietary software {#expensive-proprietary-software}
<NA>

## Asking volunteers to count birds {#asking-volunteers-to-count-birds}
<https://www.huffpost.com/entry/counting-birds-over-a-cen_b_12487152>

## Verifiable results {#verifiable-results}
<NA>

## Sloppy peer-review {#sloppy-peer-review}
<NA>

## A crashed hard drive {#a-crashed-hard-drive}
<NA>

## Cherry-picking results {#cherry-picking-results}
<NA>

## Public WiFi {#public-wi-fi}
<NA>

## Citing Wikipedia {#citing-wikipedia}
<NA>

## Pseudoscience influencers {#pseudoscience-influencers}
<https://www.jmir.org/2024/1/e38786>

## My supervisor said so {#my-supervisor-said-so}
<NA>

# Technical term cards
## Accessible {#accessible}
<NA>

## Article Processing Charge {#article-processing-charge}
<https://vu.nl/en/about-vu/divisions/university-library/more-about/gold-open-access-deals-with-publishers>

## Artificial Intelligence {#artificial-intelligence}
<NA>

## Author Accepted Manuscript {#author-accepted-manuscript}
<NA>

## Barcelona Declaration {#barcelona-declaration}
<https://barcelona-declaration.org/>

## Bibliodiversity {#bibliodiversity}
<NA>

## CARE {#care}
<https://doi.org/10.1038/s41597-021-00892-0>

## CRediT {#credit}
<https://credit.niso.org/>

## CWTS Leiden Ranking {#cwts-leiden-ranking}
<NA>

## Citizen science {#citizen-science}
<https://citizenscience.nl/p/wat-is-citizen-science>

## Code Review {#code-review}
<NA>

## Community-led {#community-led}
<https://doi.org/10.53962/k06w-2ket>

## Copyright {#copyright}
<NAhttps://uba.uva.nl/en/support/copyright/researchers/researchers.html>

## Data Management Plan {#data-management-plan}
<https://open-science.cwts.nl/introduction/open-data-software-and-infrastructures/data-management-plans>

## Data Steward {#data-steward}
<https://openworking.wordpress.com/2024/08/27/from-researcher-to-data-steward-how-to-get-started/>

## Digital Competence Centre {#digital-competence-centre}
<https://www.surf.nl/en/magazine/digital-competence-centres-let-institutions-collaborate-more-intensively>

## Embargo period {#embargo-period}
<NA>

## Ethical Review Board {#ethical-review-board}
<https://en.wikipedia.org/wiki/Institutional_review_board>

## FAIR {#fair}
<https://www.go-fair.org/fair-principles/>

## Findable {#findable}
<NA>

## Funder requirements {#funder-requirements}
<NA>

## GDPR {#gdpr}
<NA>

## Impact factor {#impact-factor}
<NA>

## Institutional repository {#institutional-repository}
<NA>

## Interoperable {#interoperable}
<NA>

## Linked Data {#linked-data}
<NA>

## Metadata {#metadata}
<https://www.tudelft.nl/en/library/research-data-management/r/manage/collect-and-document>

## Non-exclusive license {#non-exclusive-license}
<NA>

## Open Access {#open-access}
<NA>

## Open Infrastructure {#open-infrastructure}
<NA>

## Open Peer Review {#open-peer-review}
<NA>

## Open Science {#open-science}
<NA>

## Open Science Communities {#open-science-communities}
<NA>

## Open Source {#open-source}
<NA>

## Open education {#open-education}
<NA>

## Overlay journal {#overlay-journal}
<NA>

## Paywall {#paywall}
<https://archive.org/details/PaywallTheBusinessOfScholarshipFinalMovieMastered>

## Persistent identifier {#persistent-identifier}
<NA>

## Predatory journal {#predatory-journal}
<https://www.predatoryjournals.org/>

## Preprint {#preprint}
<https://doi.org/10.5281/zenodo.5600535>

## Preregistration {#preregistration}
<https://www.cos.io/initiatives/prereg>

## Publish or Perish {#publish-or-perish}
<https://en.wikipedia.org/wiki/Publish_or_perish>

## Publish, review, curate {#publish-review-curate}
<https://www.coalition-s.org/blog/peer-reviewed-preprints-and-the-publish-review-curate-model/>

## Recognition and rewards {#recognition-and-rewards}
<https://recognitionrewards.nl/>

## Registered report {#registered-report}
<https://www.cos.io/initiatives/registered-reports>

## Replication {#replication}
<NA>

## Replication Crisis {#replication-crisis}
<https://en.wikipedia.org/wiki/Replication_crisis>

## Reproducible {#reproducible}
<NA>

## Research Cycle {#research-cycle}
<NA>

## Research Software {#research-software}
<NA>

## Research Software Engineer {#research-software-engineer}
<https://doi.org/10.5281/zenodo.7994286>

## Retraction watch {#retraction-watch}
<https://retractionwatch.com/>

## Reusable {#reusable}
<NA>

## Reviewer Fatigue {#reviewer-fatigue}
<https://www.cambridge.org/core/journals/ps-political-science-and-politics/article/reviewer-fatigue-why-scholars-decline-to-review-their-peers-work/762AE347CF96E6FD20DB64B1C0D48C25>

## Rights Retention Strategy {#rights-retention-strategy}
<https://vu.nl/en/about-vu/divisions/university-library/more-about/rights-retention-strategy>

## Science Communication {#science-communication}
<NA>

## Self-archiving {#self-archiving}
<NA>

## Societal impact {#societal-impact}
<NA>

## Software Management Plan {#software-management-plan}
<https://zenodo.org/records/7589725>

## Software repository {#software-repository}
<NA>

## Taverne {#taverne}
<https://library.maastrichtuniversity.nl/research/publishing/information/sharing-research-outputs/taverne/>

## Team science {#team-science}
<https://doi.org/10.36850/mr8>

## Transparency {#transparency}
<NA>

## Version Control {#version-control}
<NA>

## Zenodo {#zenodo}
<https://zenodo.org/>
