---
title: Technical cards
---

## Accessible {#accessible}
According to the [Go FAIR initiative](https://www.go-fair.org/fair-principles/), FAIR research data should be made *accessible* in the following ways: 

> Once the user finds the required data, she/he/they need to know how they can be accessed, possibly including authentication and authorisation.
> 
> A1. (Meta)data are retrievable by their identifier using a standardised communications protocol
>
> A1.1 The protocol is open, free, and universally implementable
>
> A1.2 The protocol allows for an authentication and authorisation procedure, where necessary
>
> A2. Metadata are accessible, even when the data are no longer available

[FAIR software](https://fair-software.nl/) gives five practical recommendations to make your code FAIR.

## Article Processing Charge {#article-processing-charge}
<https://vu.nl/en/about-vu/divisions/university-library/more-about/gold-open-access-deals-with-publishers>

## Artificial Intelligence {#artificial-intelligence}
<NA>

## Author Accepted Manuscript {#author-accepted-manuscript}
<NA>

## Barcelona Declaration {#barcelona-declaration}
<https://barcelona-declaration.org/>

## Bibliodiversity {#bibliodiversity}
<NA>

## CARE {#care}
<https://doi.org/10.1038/s41597-021-00892-0>

## CRediT {#credit}
<https://credit.niso.org/>

## CWTS Leiden Ranking {#cwts-leiden-ranking}
<NA>

## Citizen science {#citizen-science}
<https://citizenscience.nl/p/wat-is-citizen-science>

## Code Review {#code-review}
<NA>

## Community-led {#community-led}
<https://doi.org/10.53962/k06w-2ket>

## Copyright {#copyright}
<NAhttps://uba.uva.nl/en/support/copyright/researchers/researchers.html>

## Data Management Plan {#data-management-plan}
<https://open-science.cwts.nl/introduction/open-data-software-and-infrastructures/data-management-plans>

## Data Steward {#data-steward}
<https://openworking.wordpress.com/2024/08/27/from-researcher-to-data-steward-how-to-get-started/>

## Digital Competence Centre {#digital-competence-centre}
<https://www.surf.nl/en/magazine/digital-competence-centres-let-institutions-collaborate-more-intensively>

## Embargo period {#embargo-period}
<NA>

## Ethical Review Board {#ethical-review-board}
<https://en.wikipedia.org/wiki/Institutional_review_board>

## FAIR {#fair}
In 2026 Wilkinson et al. argued:

> There is an urgent need to improve the infrastructure supporting the reuse of scholarly data. A diverse set of stakeholders—representing academia, industry, funding agencies, and scholarly publishers—have come together to design and jointly endorse a concise and measureable set of principles that we refer to as the FAIR Data Principles.

FAIR stands for Findable, Accessible, Interoperable and Reusable.

The [Go FAIR initiative](https://www.go-fair.org/fair-principles/), gives a great overview on how data can be made FAIR. [FAIR software](https://fair-software.nl/) gives five practical recommendations to make your code FAIR.

<https://www.go-fair.org/fair-principles/>

## Findable {#findable}
According to the [Go FAIR initiative](https://www.go-fair.org/fair-principles/), FAIR research data should be made *findable* in the following ways: 

> The first step in (re)using data is to find them. Metadata and data should be easy to find for both humans and computers. Machine-readable metadata are essential for automatic discovery of datasets and services, so this is an essential component of the FAIRification process.
> 
> F1. (Meta)data are assigned a globally unique and persistent identifier
> 
> F2. Data are described with rich metadata (defined by R1 below)
> 
> F3. Metadata clearly and explicitly include the identifier of the data they describe
> 
> F4. (Meta)data are registered or indexed in a searchable resource

[FAIR software](https://fair-software.nl/) gives five practical recommendations to make your code FAIR.

## Funder requirements {#funder-requirements}
<NA>

## GDPR {#gdpr}
<NA>

## Impact factor {#impact-factor}
<NA>

## Institutional repository {#institutional-repository}
<NA>

## Interoperable {#interoperable}
According to the [Go FAIR initiative](https://www.go-fair.org/fair-principles/), FAIR research data should be made *interoperable* in the following ways: 

> The data usually need to be integrated with other data. In addition, the data need to interoperate with applications or workflows for analysis, storage, and processing.
>
> I1. (Meta)data use a formal, accessible, shared, and broadly applicable language for knowledge representation.
> 
> I2. (Meta)data use vocabularies that follow FAIR principles
> 
> I3. (Meta)data include qualified references to other (meta)data

[FAIR software](https://fair-software.nl/) gives five practical recommendations to make your code FAIR.

## Linked Data {#linked-data}
<NA>

## Metadata {#metadata}
<https://www.tudelft.nl/en/library/research-data-management/r/manage/collect-and-document>

## Non-exclusive license {#non-exclusive-license}
<NA>

## Open Access {#open-access}
<NA>

## Open Infrastructure {#open-infrastructure}
<NA>

## Open Peer Review {#open-peer-review}
<NA>

## Open Science {#open-science}
<NA>

## Open Science Communities {#open-science-communities}
<NA>

## Open Source {#open-source}
<NA>

## Open education {#open-education}
<NA>

## Overlay journal {#overlay-journal}
<NA>

## Paywall {#paywall}
<https://archive.org/details/PaywallTheBusinessOfScholarshipFinalMovieMastered>

## Persistent identifier {#persistent-identifier}
<NA>

## Predatory journal {#predatory-journal}
<https://www.predatoryjournals.org/>

## Preprint {#preprint}
<https://doi.org/10.5281/zenodo.5600535>

## Preregistration {#preregistration}
<https://www.cos.io/initiatives/prereg>

## Publish or Perish {#publish-or-perish}
<https://en.wikipedia.org/wiki/Publish_or_perish>

## Publish, review, curate {#publish-review-curate}
<https://www.coalition-s.org/blog/peer-reviewed-preprints-and-the-publish-review-curate-model/>

## Recognition and rewards {#recognition-and-rewards}
<https://recognitionrewards.nl/>

## Registered report {#registered-report}
<https://www.cos.io/initiatives/registered-reports>

## Replication {#replication}
<NA>

## Replication Crisis {#replication-crisis}
<https://en.wikipedia.org/wiki/Replication_crisis>

## Reproducible {#reproducible}
<NA>

## Research Cycle {#research-cycle}
<NA>

## Research Software {#research-software}
<NA>

## Research Software Engineer {#research-software-engineer}
<https://doi.org/10.5281/zenodo.7994286>

## Retraction watch {#retraction-watch}
<https://retractionwatch.com/>

## Reusable {#reusable}
According to the [Go FAIR initiative](https://www.go-fair.org/fair-principles/), FAIR research data should be made *reusable* in the following ways: 

> The ultimate goal of FAIR is to optimise the reuse of data. To achieve this, metadata and data should be well-described so that they can be replicated and/or combined in different settings.
>
> R1. (Meta)data are richly described with a plurality of accurate and relevant attributes
> 
> R1.1. (Meta)data are released with a clear and accessible data usage license
> 
> R1.2. (Meta)data are associated with detailed provenance
> 
> R1.3. (Meta)data meet domain-relevant community standards

For research software [FAIR software](https://fair-software.nl/) gives five practical recommendations to make your work FAIR.

## Reviewer Fatigue {#reviewer-fatigue}
<https://www.cambridge.org/core/journals/ps-political-science-and-politics/article/reviewer-fatigue-why-scholars-decline-to-review-their-peers-work/762AE347CF96E6FD20DB64B1C0D48C25>

## Rights Retention Strategy {#rights-retention-strategy}
<https://vu.nl/en/about-vu/divisions/university-library/more-about/rights-retention-strategy>

## Science Communication {#science-communication}
<NA>

## Self-archiving {#self-archiving}
<NA>

## Societal impact {#societal-impact}
<NA>

## Software Management Plan {#software-management-plan}
<https://zenodo.org/records/7589725>

## Software repository {#software-repository}
<NA>

## Taverne {#taverne}
<https://library.maastrichtuniversity.nl/research/publishing/information/sharing-research-outputs/taverne/>

## Team science {#team-science}
<https://doi.org/10.36850/mr8>

## Transparency {#transparency}
<NA>

## Version Control {#version-control}
<NA>

## Zenodo {#zenodo}
<https://zenodo.org/>

