on:
    workflow_dispatch:
    push:
      branches: main
      paths:
        - 'README.qmd'
        - '_rules.md'
        - '_goal.md'
  
name: Quarto Publish
  
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render README.qmd
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: README.qmd

      - name: commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -am 'update responses' || echo "No changes to commit"
          git push origin || echo "No changes to commit"